delete from Algorythm;

INSERT INTO Algorythm (NAME,TYPE,BLOC,KEY_LENGTH,CREATIONYEAR,CREATEDBY,STRUCTURE,KNOWN_ATTACKS,CREATED_DATE,MODIFIED_DATE,USER_CREATION,USER_MODIFICATION)
	VALUES('Algo Test','symétrique','8-4096','56',2000,'Inconnu','schéma de Feistel','Pierre Papier Ciseaux,attaque par force brute',now(),now(),'PASCAL-L','PASCAL-L');
INSERT INTO Algorythm (NAME,TYPE,BLOC,KEY_LENGTH,CREATIONYEAR,CREATEDBY,STRUCTURE,KNOWN_ATTACKS,CREATED_DATE,MODIFIED_DATE,USER_CREATION,USER_MODIFICATION)
	VALUES('Algo Test2','symétrique','117','112-168',2000,'Inconnu','schéma de Feistel','Pierre, Papier, Ciseaux',now(),now(),'PASCAL-L','PASCAL-L');